from .antaranews import AntaranewsScraper
from .bloombergtechnoz import BloombergTechnozScraper
from .cnbcindonesia import CNBCScraper
from .detik import DetikScraper
from .jawapos import JawaposScraper
from .katadata import KatadataScraper
from .kompas import KompasScraper
from .kontan import KontanScraper
from .mediaindonesia import MediaIndonesiaScraper
from .metrotvnews import MetrotvnewsScraper
from .okezone import OkezoneScraper
from .tempo import TempoScraper
from .viva import VivaScraper
