from .bisnisindonesia import BisnisIndonesiaScraper
from .bloombergtechnoz import BloombergTechnozScraper
from .cnbcindonesia import CNBCScraper
from .detik import DetikScraper
from .katadata import KatadataScraper
from .kompas import KompasScraper
from .kontan import KontanScraper
from .metrotvnews import MetrotvnewsScraper
from .tempo import TempoScraper
from .viva import VivaScraper
